"""
Rule-based procedural timelines, one per CaseType.

These are intentionally NOT generated by the LLM. Procedural steps are the
one part of this feature where a hallucination could genuinely mislead
someone about a legal deadline, so the sequence of stages is a fixed,
human-authored template. Only the "current stage" pointer and the key dates
attached to it come from the specific document that was analyzed.

This is a simplified, general-purpose sequence for common case types and is
not a substitute for the actual procedural rules of a specific court or Act.
"""
from legal.enums import CaseType
from legal.models import TimelineStage

CONSUMER_COMPLAINT: list[TimelineStage] = [
    TimelineStage(
        key="notice_reply", title="Reply to Notice", typical_duration="15 days",
        responsible_party="You (the recipient)",
        documents_needed=["Copy of the notice", "Purchase/invoice proof", "Any correspondence with the seller"],
        what_happens="You send a written response accepting, disputing, or asking for more information about the notice.",
        if_missed="The other side may proceed to file a formal complaint without your response on record.",
    ),
    TimelineStage(
        key="complaint_filed", title="Complaint Filed at Consumer Forum", typical_duration="1–2 weeks to register",
        responsible_party="Complainant / Consumer Commission registry",
        documents_needed=["Complaint copy", "Court fee receipt", "Evidence annexures"],
        what_happens="The complaint is registered and given a case number.",
        if_missed="Not applicable — this stage is initiated by the forum once filing is complete.",
    ),
    TimelineStage(
        key="admission", title="Admission Hearing", typical_duration="2–6 weeks after filing",
        responsible_party="Consumer Commission",
        documents_needed=["Original complaint", "ID proof"],
        what_happens="The commission checks if the complaint meets basic requirements and admits it for hearing.",
        if_missed="If the complainant doesn't appear, the complaint can be dismissed for non-prosecution.",
    ),
    TimelineStage(
        key="notice_to_opposite_party", title="Notice to Opposite Party", typical_duration="30 days to respond",
        responsible_party="Consumer Commission / Opposite party",
        documents_needed=["Written version / reply"],
        what_happens="The seller/service provider is notified and given a chance to respond in writing.",
        if_missed="If the opposite party doesn't respond, the commission can proceed ex-parte.",
    ),
    TimelineStage(
        key="evidence", title="Evidence Stage", typical_duration="1–3 months",
        responsible_party="Both parties",
        documents_needed=["Affidavits", "Supporting documents", "Expert reports if any"],
        what_happens="Both sides submit evidence in the form of affidavits and documents.",
        if_missed="Missing evidence deadlines can weaken your case or lead to it being decided without your evidence.",
    ),
    TimelineStage(
        key="arguments", title="Final Arguments", typical_duration="2–4 weeks",
        responsible_party="Both parties / lawyers",
        documents_needed=["Written arguments / synopsis"],
        what_happens="Both sides present oral and/or written arguments summarizing their case.",
        if_missed="The commission may decide based on the record alone.",
    ),
    TimelineStage(
        key="judgment", title="Order / Judgment", typical_duration="Varies",
        responsible_party="Consumer Commission",
        documents_needed=[],
        what_happens="The commission passes its final order.",
        if_missed="Not applicable.",
    ),
]

CIVIL_SUIT: list[TimelineStage] = [
    TimelineStage(
        key="plaint_filed", title="Plaint Filed", typical_duration="Day 0",
        responsible_party="Plaintiff", documents_needed=["Plaint", "Court fee", "List of documents"],
        what_happens="The lawsuit is formally filed in civil court.",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="summons", title="Summons to Defendant", typical_duration="30 days to appear",
        responsible_party="Court / Defendant",
        documents_needed=["Vakalatnama (if via lawyer)", "Written statement"],
        what_happens="The defendant is formally notified and must respond.",
        if_missed="Court can proceed ex-parte if the defendant doesn't appear after valid service.",
    ),
    TimelineStage(
        key="written_statement", title="Written Statement Filed", typical_duration="Within 30–90 days",
        responsible_party="Defendant",
        documents_needed=["Written statement", "Supporting documents"],
        what_happens="Defendant files their defence in writing.",
        if_missed="Court may treat the claim as admitted on points not specifically denied.",
    ),
    TimelineStage(
        key="framing_issues", title="Framing of Issues", typical_duration="Varies",
        responsible_party="Court", documents_needed=[],
        what_happens="The judge identifies the exact questions of fact and law to be decided.",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="evidence", title="Evidence Stage", typical_duration="Several months",
        responsible_party="Both parties",
        documents_needed=["Witness list", "Affidavits of evidence", "Original documents"],
        what_happens="Witnesses are examined and cross-examined; documents are proved.",
        if_missed="Failure to produce evidence/witnesses can seriously weaken your case.",
    ),
    TimelineStage(
        key="arguments", title="Final Arguments", typical_duration="Varies",
        responsible_party="Both parties / lawyers", documents_needed=["Written submissions"],
        what_happens="Final arguments are made before the judge.",
        if_missed="Court may decide based on the record.",
    ),
    TimelineStage(
        key="judgment", title="Judgment & Decree", typical_duration="Varies",
        responsible_party="Court", documents_needed=[],
        what_happens="The court delivers judgment and passes a decree.",
        if_missed="Not applicable.",
    ),
]

CRIMINAL_FIR: list[TimelineStage] = [
    TimelineStage(
        key="fir_registered", title="FIR Registered", typical_duration="Day 0",
        responsible_party="Police", documents_needed=["FIR copy"],
        what_happens="Police formally record the complaint as an FIR.",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="investigation", title="Police Investigation", typical_duration="Typically 60–90 days",
        responsible_party="Investigating Officer",
        documents_needed=["Statements", "Evidence collected", "Medical/forensic reports if any"],
        what_happens="Police gather evidence, record statements, and may make arrests.",
        if_missed="Delays here can be flagged to the Magistrate or via a protest petition.",
    ),
    TimelineStage(
        key="chargesheet", title="Chargesheet Filed", typical_duration="Within statutory period",
        responsible_party="Police / Prosecution",
        documents_needed=["Chargesheet", "List of witnesses/evidence"],
        what_happens="Police file the chargesheet in court if there's enough evidence to proceed.",
        if_missed="If no chargesheet is filed in time, the accused may be entitled to statutory bail.",
    ),
    TimelineStage(
        key="cognizance_framing", title="Cognizance & Framing of Charges", typical_duration="Varies",
        responsible_party="Magistrate/Court", documents_needed=[],
        what_happens="Court takes cognizance and formally frames charges against the accused.",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="trial_evidence", title="Trial — Evidence & Cross-Examination", typical_duration="Several months to years",
        responsible_party="Prosecution / Defence",
        documents_needed=["Witness list", "Evidence"],
        what_happens="Prosecution and defence present evidence and examine witnesses.",
        if_missed="Missing hearing dates can lead to warrants or adverse inferences.",
    ),
    TimelineStage(
        key="final_arguments", title="Final Arguments", typical_duration="Varies",
        responsible_party="Both sides", documents_needed=[],
        what_happens="Both sides argue on the evidence on record.",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="judgment", title="Judgment", typical_duration="Varies",
        responsible_party="Court", documents_needed=[],
        what_happens="Court pronounces acquittal or conviction (and sentencing, if convicted).",
        if_missed="Not applicable.",
    ),
]

RTI_APPLICATION: list[TimelineStage] = [
    TimelineStage(
        key="application_filed", title="RTI Application Filed", typical_duration="Day 0",
        responsible_party="Applicant", documents_needed=["RTI application", "Fee receipt"],
        what_happens="Application is submitted to the Public Information Officer (PIO).",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="pio_response", title="PIO's Response Due", typical_duration="30 days (48 hrs if life/liberty involved)",
        responsible_party="Public Information Officer",
        documents_needed=[],
        what_happens="PIO must supply the information or give valid grounds for refusal.",
        if_missed="If there's no response, you can file a first appeal.",
    ),
    TimelineStage(
        key="first_appeal", title="First Appeal", typical_duration="Within 30 days of refusal/non-response",
        responsible_party="Applicant / Appellate Authority",
        documents_needed=["Appeal letter", "Copy of original application"],
        what_happens="A senior officer reviews the PIO's decision or inaction.",
        if_missed="You can still move to the Information Commission, but acting sooner is safer.",
    ),
    TimelineStage(
        key="second_appeal", title="Second Appeal to Information Commission", typical_duration="Within 90 days",
        responsible_party="Applicant / State or Central Information Commission",
        documents_needed=["Both prior applications", "Appeal memo"],
        what_happens="The Information Commission can direct disclosure and even impose penalties on the PIO.",
        if_missed="Not applicable.",
    ),
]

FAMILY_MATRIMONIAL: list[TimelineStage] = [
    TimelineStage(
        key="petition_filed", title="Petition Filed", typical_duration="Day 0",
        responsible_party="Petitioner", documents_needed=["Petition", "Marriage certificate", "Address proof"],
        what_happens="The petition (divorce, maintenance, custody, etc.) is filed in family court.",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="notice", title="Notice to Other Party", typical_duration="30 days to respond",
        responsible_party="Court / Respondent", documents_needed=["Reply/written statement"],
        what_happens="The other spouse is notified and given a chance to respond.",
        if_missed="Court may proceed ex-parte after valid service.",
    ),
    TimelineStage(
        key="mediation", title="Mediation / Counselling", typical_duration="Often mandatory, 1–3 sessions",
        responsible_party="Family Court Counsellor", documents_needed=[],
        what_happens="Court-appointed counsellors attempt reconciliation or settlement first.",
        if_missed="Skipping mandated sessions can delay the case further.",
    ),
    TimelineStage(
        key="evidence", title="Evidence Stage", typical_duration="Several months",
        responsible_party="Both parties", documents_needed=["Affidavits", "Financial documents if maintenance is involved"],
        what_happens="Both sides present evidence relevant to the claims.",
        if_missed="Missing evidence can weaken claims for maintenance/custody.",
    ),
    TimelineStage(
        key="arguments", title="Final Arguments", typical_duration="Varies",
        responsible_party="Both parties", documents_needed=[],
        what_happens="Final arguments before the judge.",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="judgment", title="Judgment / Order", typical_duration="Varies",
        responsible_party="Family Court", documents_needed=[],
        what_happens="Court passes its order.",
        if_missed="Not applicable.",
    ),
]

GENERIC: list[TimelineStage] = [
    TimelineStage(
        key="response_due", title="Respond to the Document", typical_duration="Check the document for the exact deadline",
        responsible_party="You", documents_needed=["The document itself", "Any proof relevant to your response"],
        what_happens="You typically need to formally acknowledge or respond within a set window.",
        if_missed="Missing this can limit your options later, so respond in writing if in doubt.",
    ),
    TimelineStage(
        key="filing_admission", title="Filing / Admission", typical_duration="Varies",
        responsible_party="Court/Authority", documents_needed=[],
        what_happens="The matter is formally registered/admitted for hearing.",
        if_missed="Not applicable.",
    ),
    TimelineStage(
        key="evidence", title="Evidence / Document Stage", typical_duration="Varies",
        responsible_party="Both parties", documents_needed=["Relevant supporting documents"],
        what_happens="Both sides submit supporting material.",
        if_missed="Missing evidence deadlines can weaken your position.",
    ),
    TimelineStage(
        key="hearing_decision", title="Hearing & Decision", typical_duration="Varies",
        responsible_party="Court/Authority", documents_needed=[],
        what_happens="A hearing is held and a decision is issued.",
        if_missed="Not applicable.",
    ),
]

TEMPLATES: dict[CaseType, list[TimelineStage]] = {
    CaseType.CONSUMER_COMPLAINT: CONSUMER_COMPLAINT,
    CaseType.CIVIL_SUIT: CIVIL_SUIT,
    CaseType.CRIMINAL_FIR: CRIMINAL_FIR,
    CaseType.RTI_APPLICATION: RTI_APPLICATION,
    CaseType.FAMILY_MATRIMONIAL: FAMILY_MATRIMONIAL,
    CaseType.PROPERTY_DISPUTE: CIVIL_SUIT,   # property disputes generally follow civil suit procedure
    CaseType.LABOUR_EMPLOYMENT: GENERIC,
    CaseType.OTHER: GENERIC,
}


def get_timeline(case_type: CaseType, current_stage_key: str | None = None) -> list[TimelineStage]:
    template = TEMPLATES.get(case_type, GENERIC)
    stages = [s.model_copy() for s in template]
    if current_stage_key:
        for s in stages:
            s.is_current = (s.key == current_stage_key)
    elif stages:
        stages[0].is_current = True
    return stages
